### PR TITLE
DATAREST-1143 - throw a ResourceNotFoundException instead of returning an http response with status code directly

### PR DESCRIPTION
**Pull request by jreijn**
Changed getItemResource to throw a ResourceNotFoundException instead of returning an empty ResponseEntity with a status code when an item can't be found. This will allow projects to use a ResponseEntityExceptionHandler and create a custom error message for 404 responses on GET requests, which is not possible at the moment.

- [x] You have read the [Spring Data contribution guidelines](https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.adoc).
- [x] There is a ticket in the bug tracker for the project in our [JIRA](https://jira.spring.io/browse/DATAREST).
- [x] You use the code formatters provided [here](https://github.com/spring-projects/spring-data-build/tree/master/etc/ide) and have them applied to your changes. Don’t submit any formatting related changes.
- [x] You submit test cases (unit or integration tests) that back your changes.
- [x] You added yourself as author in the headers of the classes you touched. Amend the date range in the Apache license header if needed. For new types, add the license header (copy from another file and set the current year only).

### CODE REVIEW

**Comment by jreijn** [comment]
As this is my first contribution to spring-data all feedback is welcome.

**Comment by jreijn** [comment]
Is there anything I need to do to move this forward?

**Comment by jamarciano** [comment]
Is there anything preventing this from being merged going forward?

It would be very nice to be able to handle these exceptions normally; the alternatives aren't very intuitive and don't work quite as well as this would.

**Comment by pkostrzewa** [comment]
@odrotbohm Any thoughts on this?

**Comment by odrotbohm** [comment]
Sorry, this took so long. I'll schedule this for inclusion into Moore M2 (Spring Data REST 3.2).

**Comment by odrotbohm** [comment]
In place now.

**Pull request closed without merging**
