### PR TITLE
Log exception even if it has no message. Fix DATAREST-539

### PR DESCRIPTION
**Pull request by avandecreme**

### CODE REVIEW

**Comment by avandecreme** [comment]
UP!
@olivergierke any thought on that?

Right now it is quite hard to debug NPE because they have no message.

**Comment by avandecreme** [comment]
No interest in it?

**Comment by avandecreme** [comment]
Nevermind, I didn't see you merged without using Github's pull request system.

**Comment by olivergierke** [comment]
:) :+1:

**Comment by gregturn** [comment]
@avandecreme Yeah. In case you haven't noticed, we use pull requests to submit patches. But we use git cherry-pick for the actual merging, for several reasons.

**Pull request closed without merging**
