### PR TITLE
DATAREST-1338 - Enable JsonPatch support to traverse Map keys.

### PR DESCRIPTION
**Pull request by odrotbohm**

### CODE REVIEW

**Comment by mle-enso** [comment]
Awesome, thank you!

**Comment by Kerruba** [comment]
Any update on this @odrotbohm? Thanks

**Comment by prats2017** [comment]
Hi, I am so sorry for posting here. I couldn't find a way to post my query.
Can someone please look at https://stackoverflow.com/questions/61069179/json-patch-update-nested-an-attribute-in-nested-object

**Comment by prats2017** [comment]
Hi, I am so sorry for posting here. I couldn't find a way to post my query.
Can someone please look at https://stackoverflow.com/questions/61069179/json-patch-update-nested-an-attribute-in-nested-object

**Comment by odrotbohm** [comment]
That's already been merged a long while ago.

**Pull request closed without merging**
