### PR TITLE
DATAREST-1077: Pass headers from HAL.client on requests

### PR DESCRIPTION
**Pull request by gregorycfrank**
Pass headers from HAL.client on requests so custom request headers aren't lost.

E.g. custom Authorization: bearer <token> headers

- [ ] You have read the [Spring Data contribution guidelines](https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.adoc).
- [ ] There is a ticket in the bug tracker for the project in our [JIRA](https://jira.spring.io/browse/DATAREST).
- [ ] You use the code formatters provided [here](https://github.com/spring-projects/spring-data-build/tree/master/etc/ide) and have them applied to your changes. Don’t submit any formatting related changes.
- [ ] You submit test cases (unit or integration tests) that back your changes.
- [ ] You added yourself as author in the headers of the classes you touched. Amend the date range in the Apache license header if needed. For new types, add the license header (copy from another file and set the current year only).

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@gregorycfrank Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-rest&pullRequestId=267)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-data-rest&pullRequestId=267) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@gregorycfrank Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-rest&pullRequestId=267)!

**Comment by gregturn** [comment]
Thanks @gregorycfrank. Well take it from here.

**Comment by gregturn** [comment]
Resolved via https://github.com/spring-projects/spring-data-rest/commit/56f34ec1b1bdcc7ee0db6a5c71d6f536f3687941.

Thanks @gregorycfrank!

**Pull request closed without merging**
