### PR TITLE
Update ResourceMetadataHandlerMethodArgumentResolver.java

### PR DESCRIPTION
**Pull request by yangjiacheng**
fix： ResourceMetadataHandlerMethodArgumentResolver un support ResourceMetadata classType arguments and mismatch param type

* i read
* just i want fix it，because i work with spring rest and it make some troble for me or other
* spring tools suite
* only one line code
* jiacheng Yang

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@yangjiacheng Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-rest&pullRequestId=296)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-data-rest&pullRequestId=296) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@yangjiacheng Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-rest&pullRequestId=296)!

**Comment by yangjiacheng** [comment]
@olivergierke if my edited is a mistake or you have better suggestions，please fast fix，the bug is ： ResourceMetadataHandlerMethodArgumentResolver  supportsParamete`s predicate is parameteType shuold Assignable to RepositoryInformation.class but argumentResolver process return type is ResourceMetadata, so when i definition RepositoryInformation type argument in controller，throw missMatcher param exception，or i  definition ResourceMetadata type argument in controller，no HandlerMethodArgumentResolver support。it·s affecting my work

**Comment by olivergierke** [comment]
That's merged and backported, thanks!

**Pull request closed without merging**
