### PR TITLE
DATAREST-1119: Remove profile link in case ALPS is disabled

### PR DESCRIPTION
**Pull request by jreijn**
- [x] You have read the [Spring Data contribution guidelines](https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.adoc).
- [x] There is a ticket in the bug tracker for the project in our [JIRA](https://jira.spring.io/browse/DATAREST).
- [ ] You use the code formatters provided [here](https://github.com/spring-projects/spring-data-build/tree/master/etc/ide) and have them applied to your changes. Don’t submit any formatting related changes.
- [ ] You submit test cases (unit or integration tests) that back your changes.
- [ ] You added yourself as author in the headers of the classes you touched. Amend the date range in the Apache license header if needed. For new types, add the license header (copy from another file and set the current year only).

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@jreijn Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-rest&pullRequestId=280)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-data-rest&pullRequestId=280) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@jreijn Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-rest&pullRequestId=280)!

**Comment by anton-ff** [comment]
May I know why this fix had been removed from newest release?

**Comment by gregturn** [comment]
This issue was opened in 2017. I just scanned the commits going back to December 2016 and see no record of it being merged to master. Nor do I see any comments on the related JIRA issue about it being picked up by the Spring Data team.

**Comment by TallGnome** [comment]
Is there any solution or workaround for this issue for the latest version?

**Comment by falk-stefan** [comment]
Still an issue in 2023..

**Pull request closed without merging**
