### PR TITLE
Update projections-excerpts.adoc

### PR DESCRIPTION
**Pull request by tcrossland**
Corrected a tiny spelling mistake

### CODE REVIEW

**Comment by gregturn** [comment]
Have you signed Spring's CLA form?

**Comment by gregturn** [comment]
I've created https://jira.spring.io/browse/DATAREST-484 to track this issue in JIRA.

**Comment by tcrossland** [comment]
I've just signed and submitted the form and updated the ticket in JIRA. Having to sign an agreement to submit a spelling correction seems excessive (or a good way to discourage contributions from the community).

**Comment by gregturn** [comment]
@tcrossland Sorry about that. I wasn't sure if we had a threshold or not for small edits, so I played it safe.

**Comment by tcrossland** [comment]
@gregturn No problem, hopefully will make further use of the CLA at some point in the future.

**Pull request closed without merging**
