### PR TITLE
DATAREST-925 - Invoke ResourceProcessor's for ProjectionResource's

### PR DESCRIPTION
**Pull request by candrews**
DATAREST-925 - Invoke ResourceProcessor's for ProjectionResource's

https://jira.spring.io/browse/DATAREST-925

### CODE REVIEW

**Comment by olivergierke** [comment]
I guess we at least need some test that verify that the processors are invoked, i.e. some additional links appearing in the intended situations. There are also some minor formatting issues (spaces instead of tabs) but I could take a look at those later.

**Comment by candrews** [comment]
@olivergierke I updated this PR to fix the whitespace changes. Since `PersistentEntityJackson2Module.NestedEntitySerializer` is no longer constructed or referenced outside of `PersistentEntityJackson2Module`, I made that class package scoped.

I also ran the https://github.com/zampettim/datarest925 test case against it and verified that the results were as desired.

**Comment by candrews** [comment]
@olivergierke is this something that could be merged?

**Comment by candrews** [comment]
@olivergierke perhaps this would be a candidate for 2.5.5 and/or 2.6.0.M2?

(I kind of really need this change, if you couldn't tell already)

**Comment by olivergierke** [comment]
It will have to go the RC. And no — as indicated above already, it is not without any tests added to the PR.

**Comment by candrews** [comment]
@olivergierke I've updated the PR to include a test that fails before my change and passes after, proving that the change fixes the problem.

**Comment by candrews** [comment]
@olivergierke is there anything else I can do to help get this into the next release?

**Comment by olivergierke** [comment]
That's polished and merged. Thanks for the contribution and patience, Craig! 🙃

**Pull request closed without merging**
