### PR TITLE
DATAREST-1356 - Fix for a bug around single link PUTs introduced in 554d6cb2

### PR DESCRIPTION
**Pull request by bvulaj**
Fix for the change:
```diff
-				if (source.getLinks().size() != 1) {
+				if (source.getLinks().hasSingleLink()) {
```

https://github.com/spring-projects/spring-data-rest/commit/554d6cb27b84cebedc651a5a25b10ccfb0cf8265#diff-1d7c16fe1992fef13a47fa8ab8599718L317

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@bvulaj Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-rest&pullRequestId=354)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-data-rest&pullRequestId=354) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@bvulaj Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-rest&pullRequestId=354)!

**Comment by bvulaj** [comment]
This is still a bug in 3.2 RC - any update on merging?

**Comment by lareferencia** [comment]
Sorry, but I am having problems with this issue.  

Correct me if am wrong, but in line 321, the context is "check if is a single link since we are updating a property that is not a collection" so I think that the right line is

` if ( ! source.getLinks().hasSingleLink() ) {`
note the ! 

because the exception only must be throw if links is greater than 1

**Comment by gregturn** [comment]
Is there a test case that illustrates this? We can't move forward on a single line change that flips on a "!".

**Comment by lareferencia** [comment]
Sorry, I just discovered a pull request with the same proposal waiting to be approved. 

https://github.com/spring-projects/spring-data-rest/pull/364

**Comment by bvulaj** [comment]
https://github.com/spring-projects/spring-data-rest/pull/364 is a duplicate of this PR.

**Comment by luvarqpp** [comment]
Try to have a look at git blame just before bug was introduces: https://github.com/spring-projects/spring-data-rest/blame/ce321da80715f9201a5fa12b4385264e3e861c31/spring-data-rest-webmvc/src/main/java/org/springframework/data/rest/webmvc/RepositoryPropertyReferenceController.java#L317

To test this problem (I would write some, having a time to learn how to make some unit test instead of integration one):

* prepare entity Comment with OneToOne association to User (createdBy association)
* prepare User entity
* try to associate some author to existing Comment

Sample code snippet for last step:

```java
createCommentResponse = ...
userLink = ...

final String authorAssociationEndpoint = JsonPath.read(createCommentResponse.getResponseBody(), "$._links.createdBy.href");
log.info("Going to add single User to association endpoint for author (createdBy).");
        this.webClient.put().uri(authorAssociationEndpoint)
                .contentType(MediaType.valueOf("text/uri-list"))
                .accept(MediaTypes.HAL_JSON)
                .bodyValue(userLink)
                .exchange().expectStatus().value(is(204));
```

PS: If someone can point me to similar test, I will try to implement this one.

**Comment by lqforgithub** [comment]
if you are using spring boot 2.2.0.RELEASE, you'll have this bug. 2.1.4.RELEASE is fine.

**Comment by luvarqpp** [comment]
> Is there a test case that illustrates this? We can't move forward on a single line change that flips on a "!".

I have created two tests. One positive and one negative. It is in my version of pull request https://github.com/spring-projects/spring-data-rest/pull/364 to this bug.

**Comment by gregturn** [comment]
Resolved via https://github.com/spring-projects/spring-data-rest/commit/202a8aa30221b81dece183b74d81278deaf45321.

Thanks everyone for working hard to bring this one home. I went ahead and use #364 as the final solution.

**Pull request closed without merging**
