### PR TITLE
DATAREST-1033 - Fix DomainObjectReader's handling of polymorphic types

### PR DESCRIPTION
**Pull request by candrews**
This PR is a rebase of #260 for the master branch instead of the 2.6.x branch.

- [X] You have read the [Spring Data contribution guidelines](https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.adoc).
- [X] There is a ticket in the bug tracker for the project in our [JIRA](https://jira.spring.io/browse/DATAREST).
- [X] You use the code formatters provided [here](https://github.com/spring-projects/spring-data-build/tree/master/etc/ide) and have them applied to your changes. Don’t submit any formatting related changes.
- [X] You submit test cases (unit or integration tests) that back your changes.
- [X] You added yourself as author in the headers of the classes you touched. Amend the date range in the Apache license header if needed. For new types, add the license header (copy from another file and set the current year only).

### CODE REVIEW

**Comment by candrews** [comment]
@olivergierke com'on, please?

**Comment by candrews** [comment]
Can you please take a look at this one?
@mp911de @olivergierke @christophstrobl
I've been trying for almost a year to get this in, I'm still 🤞 hoping it can get in at some point, thank you in advance!

**Comment by candrews** [comment]
@mp911de can you or anyone else from the project please take a look at this? It's been 10 months - I'd really like to see this get in at some point.

**Comment by candrews** [comment]
I noticed there was a merge conflict, so I fixed that.

Can you please merge this PR? Another few months have passed. @mp911de  @olivergierke pretty please?

**Comment by odrotbohm** [comment]
Declined due to the reasons layed out in the original ticket.

**Pull request closed without merging**
