### PR TITLE
DATAREST-464 - Links don't get inserted for inlined _embedded associations

### PR DESCRIPTION
**Pull request by zEvg**
Disclaimer: This is my first pull request to spring projects. Hope I did everything correct.

Please review this pull request for https://jira.spring.io/browse/DATAREST-464.

### CODE REVIEW

**Comment by gregturn** [comment]
BTW, be sure to sign the Spring CLA => https://support.springsource.com/spring_committer_signup (Spring Data Access/Oliver Gierke)

**Comment by zEvg** [comment]
@gregturn, 
sure, already did.

**Comment by gregturn** [comment]
Already resolved by https://github.com/spring-projects/spring-data-rest/commit/2697c6a2fa481f172218bbff603b7385e4bf85b2 and https://jira.spring.io/browse/DATAREST-302

**Comment by zEvg** [comment]
Thanks, guys!
Will take a look.

**Pull request closed without merging**
