### PR TITLE
DATAREST-1356 Fix updating single associations (second pull req for same isue)

### PR DESCRIPTION
**Pull request by luvarqpp**
There is an bug introduced a few months ago. This commit should fix it. I will try to find come time and write test.
Please let me know, if it seems to be bug also to you.
PS: According git history, there was (prior some rebase) condition like `getLinks().size() != 1`.

- [x] You have read the [Spring Data contribution guidelines](https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.adoc).
- [x] There is a ticket in the bug tracker for the project in our [JIRA](https://jira.spring.io/browse/DATAREST).
- [x] You use the code formatters provided [here](https://github.com/spring-projects/spring-data-build/tree/master/etc/ide) and have them applied to your changes. Don’t submit any formatting related changes.
- [x] You submit test cases (unit or integration tests) that back your changes.
- [x] You added yourself as author in the headers of the classes you touched. Amend the date range in the Apache license header if needed. For new types, add the license header (copy from another file and set the current year only).

### CODE REVIEW

**Comment by lareferencia** [comment]
Yes, I found this bug and commented on original "fix". I have tested and this is the right solution.

**Comment by bvulaj** [comment]
This is a duplicate of https://github.com/spring-projects/spring-data-rest/pull/354

**Comment by lqforgithub** [comment]
Must send only 1 link to update a property reference that isn't a List or a Map

what a dirty mistake!

**Comment by gregturn** [comment]
Thanks @luvarqpp!

Since your PR had the most testing, I went ahead and took it, polished it (slightly), and backported it to `3.2.x` branch.

**Comment by gregturn** [comment]
Resolved via https://github.com/spring-projects/spring-data-rest/commit/202a8aa30221b81dece183b74d81278deaf45321. Backported to `3.2.x` via https://github.com/spring-projects/spring-data-rest/commit/87f9904e3ab429ab4c1b8be95932bc7ebb362b47.

Thanks to everyone for working hard to bring this one home. 

The solution is in both `master` branch (Neumann) as well as `3.2.x` (Moore SR1).

**Comment by luvarqpp** [comment]
To use fixed version right now, I am using temporary snapshot build of artifact. Maven pom snippet:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.2.0.RELEASE</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>
    <!-- https://spring-calendar.cfapps.io/ -->

    <dependencies>
        <dependency>
            <!-- TODO temporary to fix single link association... https://github.com/spring-projects/spring-data-rest/pull/364 -->
            <groupId>org.springframework.data</groupId>
            <artifactId>spring-data-rest-webmvc</artifactId>
            <version>3.3.0.BUILD-SNAPSHOT</version>
        </dependency>
    </dependencies>

    <repositories>
        <repository>
            <id>spring-snapshot</id>
            <name>Spring Snapshot Repository</name>
            <url>https://repo.spring.io/snapshot</url>
        </repository>
        <repository>
            <id>spring-milestones</id>
            <name>Spring Milestones</name>
            <url>https://repo.spring.io/milestone</url>
        </repository>
    </repositories>
</project>
```

**Pull request closed without merging**
