### PR TITLE
[2.6.x] DATAREST-1033 - Fix DomainObjectReader's handling of polymorphic types

### PR DESCRIPTION
**Pull request by candrews**
https://jira.spring.io/browse/DATAREST-1033

### CODE REVIEW

**Comment by candrews** [comment]
@olivergierke can you please take a look at this PR?

Thanks!

**Comment by olivergierke** [comment]
Would you mind reworking the seven levels of nesting? We usually prefer early returns so that we can keep the nesting to at most one or two levels. Please remove all the `final` keywords unless really necessary.

I also wonder whether a lot of the Jackson inspection code could be moved into our `MappedProperties` type as that might introduce the possibility to cache things. 60 lines of procedural code en block are basically untestable and given the cyclomatic complexity introduced I really think we should have unit tests for that part explicitly, not only end to end object conversion tests.

We can definitely get to that. I just don't have too much time to look closer due to a pending release.

**Comment by candrews** [comment]
I've reworked the nesting in favor of early returns which reduces the level quite a bit. I've also removed the `final` keywords.

The purpose of the more complex code is to avoid UnrecognizedPropertyException - if https://github.com/spring-projects/spring-data-rest/pull/260/files#diff-63e4af7a7a88565be2f1494ede2de7abR266 is changed to read:
`return mapper.readerFor(newTargetJavaType).withoutFeatures(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES).readValue(existingTargetNode);`

Then lines [236](https://github.com/spring-projects/spring-data-rest/pull/260/files#diff-63e4af7a7a88565be2f1494ede2de7abR235) to [263](https://github.com/spring-projects/spring-data-rest/pull/260/files#diff-63e4af7a7a88565be2f1494ede2de7abR263) can be replaced with just:
```
// apply the root json. This includes the type information.
existingTargetNode.setAll(root);
```

Would that be a better liked direction?

Also, I'd love to get this change into the upcoming release you referenced!

**Comment by candrews** [comment]
@olivergierke congratulations on the 3.0M2 release!

On the topic of this issue, do you have a bit of time now? I'm sorry to be a pest, but this is a time sensitive issue. This topic is blocking my current project from its next release, so I would really like to see it be resolved. I think I've matched the coding style, provided appropriate tests, and resolved the problem in this PR, so if you could please merge these changes or provide feedback getting it closer to merging, I'd be greatly appreciative of your help.

Thank you again!

**Comment by olivergierke** [comment]
There's a couple of things still left:

- I feel uncomfortable to let `DomainObjectReader` work with so much in depth knowledge about Jackson internals. So far it's only calling read value/tree methods. Now it's all of a sudden dealing with `DeserializationContext`/`Configuration`. I am not saying we can avoid that, I'm saying this code should be abstracted so that the code necessary to implement `handlePotentialTypeChange(…)` can be less low-level.
- While I understand what the idea of this change is on a high level, I still don't quite get why all the extra stuff is necessary beyond: detect the actual target type to be created from the payload, let the `ObjectMapper` create an instance of exactly that type to merge.
- All the line comments indicate that we should probably have nested methods used for those steps.
- The most outer if can still be inverted to reduce the nesting level further.

I'm happy to take care of the implementation side things (method extractions, nesting level reductions) myself, but I need to understand why all this is necessary as I'll have to maintain it going forward.

**Comment by candrews** [comment]
I can make another PR with an alternative approach that's simpler and doesn't require Jackson specific knowledge (I described it in https://github.com/spring-projects/spring-data-rest/pull/260#issuecomment-291554135 but the PR should clarify it). Hopefully this approach will reduce these concerns.

**Comment by candrews** [comment]
@olivergierke is there anything I can do to help this issue along?

**Comment by candrews** [comment]
@olivergierke is there anything I can do to get this merged, or another fix for this issue merged?

**Comment by candrews** [comment]
The 2.6.x branch is no longer being maintained, so I'm closing this PR in favor of https://github.com/spring-projects/spring-data-rest/pull/274

**Pull request closed without merging**
